### ISSUE TITLE
Allow for Active Effects from Compendium Items to be added with the Active Effect Behaviors

### ISSUE THREAD

**Issue by maxobremer** [kaelad02/region-active-effects#5]
At the moment you cannot add active effects that are on items within a compendium to a Active Effect Behavior. It would be nice if this was possible. 

I like to combine this module with [Region Attacher](https://github.com/roth-michael/region-attacher) to set up certain spells. My current issue is with the silence spell which makes people immuun to thunder damage while in the area of effect. My idea was to create an effect on the spell and link that to the region attacher's region using the active effect behaviour of this module. but that doesnt work as it would reference an Embedded Document and cannot be retrieved synchronously because of it.
A work around is dropping the item on an actor and then dropping the effect in the behaviour but that requires work every time the spell is used.

So would it be possible to either allows this or allow you to store the active effect data in the Active Effect Behavior directly? Like make the effect within the Behaviour instead of outside of it.

Foundry v12.331
DnD5e 3.3.1
Region Active Effects 1.2.0
Region Attacher 1.4.4

**Comment by kaelad02** [comment]
Just taking a quick look at the code before testing, it should work just fine. The module references an active effect by UUID and gets it using the `fromUuid` function. Shouldn't matter whether the item the AE is on is in the world or a compendium. I'll check

**Comment by kaelad02** [comment]
I tested it and remember now. This is a core Foundry bug, where the UUID field selector is hard-coded to using the `fromUuidSync` function to verify the UUID and make sure it's pointing to the correct item type (e.g. an Active Effect). I thought there was an existing issue on their GitHub page but I'm having trouble finding it. I'll search some more and if not create an issue for it.

**Comment by maxobremer** [comment]
Sounds good. I guess its best to then close this issue. Unless you want to implement the idea of making/storing the active effect on the Active Effect Behaviour itself. Then i would rename this issue for tracking that. 

I will leave that decision to you, so close this if needed.

**Comment by kaelad02** [comment]
I couldn't find an existing issue so I filed a new one: foundryvtt/foundryvtt#11717
